sonar.verbose=true
sonar.organization=jenkins2-org
sonar.projectKey=jenkins2-org_sonar-jenkins2-pro1
sonar.projectName=sonar-jenkins2-pro1
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

